status = [
    "linting",
    "build-frontend",
    "build-docs",
    "test-windows",
    "test-linux (sqlite)",
    "test-linux (mariadb)",
    "test-linux (mysql)",
    "test-linux (postgres)",
    "test-linux (mssql)",
]
delete_merged_branches = true
